Fix some bugs introduced with in-place (jumping) calls/returns (WIP)
Backtraces are currently broken. Un-commenting lines 302 and 307 in
interp.go fixes them, but causes state-decoding to fail. The following
test results are from a run with lines 302 and 307 un-commented:

	=== RUN   TestHashtable
	--- PASS: TestHashtable (0.01s)
	=== RUN   TestListAppend
	--- PASS: TestListAppend (0.00s)
	=== RUN   TestEvalExpr
	--- PASS: TestEvalExpr (0.00s)
	=== RUN   TestExecFile
	--- PASS: TestExecFile (0.01s)
	=== RUN   TestSuspend
	--- PASS: TestSuspend (0.00s)
	=== RUN   TestParameterPassing
	--- PASS: TestParameterPassing (0.00s)
	=== RUN   TestPrint
	--- FAIL: TestPrint (0.00s)
		eval_test.go:394: output was foo.go:2: <toplevel>: hello
			foo.go:4: <toplevel>: world
			, want foo.go:2: <toplevel>: hello
			foo.go:3: f: world
	=== RUN   TestInt
	--- PASS: TestInt (0.00s)
	=== RUN   TestBacktrace
	--- FAIL: TestBacktrace (0.00s)
		eval_test.go:497: error was Traceback (most recent call last):
			  crash.sky:6: in <toplevel>
			  <builtin>:1: in min
			  crash.sky:3: in g
			  crash.sky:2: in f
			Error: floored division by zero, want Traceback (most recent
			call last):
			  crash.sky:6: in <toplevel>
			  crash.sky:5: in i
			  crash.sky:4: in h
			  <builtin>:1: in min
			  crash.sky:3: in g
			  crash.sky:2: in f
			Error: floored division by zero
	=== RUN   TestRepeatedExec
	--- PASS: TestRepeatedExec (0.00s)
	=== RUN   TestUnpackUserDefined
	--- PASS: TestUnpackUserDefined (0.00s)
	=== RUN   ExampleExecFile
	--- PASS: ExampleExecFile (0.00s)
	=== RUN   ExampleThread_Load_sequential
	--- PASS: ExampleThread_Load_sequential (0.00s)
	=== RUN   ExampleThread_Load_parallel
	--- PASS: ExampleThread_Load_parallel (0.00s)
	=== RUN   ExampleThread_Load_parallelCycle
	--- PASS: ExampleThread_Load_parallelCycle (0.00s)
	FAIL
	exit status 1
	FAIL	github.com/wdamron/skylark	0.034s

The following test results are from a run with lines 302 and 307 in
interp.go commented out:

	=== RUN   TestHashtable
	--- PASS: TestHashtable (0.01s)
	=== RUN   TestListAppend
	--- PASS: TestListAppend (0.00s)
	=== RUN   TestEvalExpr
	--- PASS: TestEvalExpr (0.00s)
	=== RUN   TestExecFile
	--- PASS: TestExecFile (0.01s)
	=== RUN   TestSuspend
	--- FAIL: TestSuspend (0.00s)
		eval_test.go:192: Codec: unexpected tag (0) while decoding value
	=== RUN   TestParameterPassing
	--- PASS: TestParameterPassing (0.00s)
	=== RUN   TestPrint
	--- PASS: TestPrint (0.00s)
	=== RUN   TestInt
	--- PASS: TestInt (0.00s)
	=== RUN   TestBacktrace
	--- PASS: TestBacktrace (0.00s)
	=== RUN   TestRepeatedExec
	--- PASS: TestRepeatedExec (0.00s)
	=== RUN   TestUnpackUserDefined
	--- PASS: TestUnpackUserDefined (0.00s)
	=== RUN   ExampleExecFile
	--- PASS: ExampleExecFile (0.00s)
	=== RUN   ExampleThread_Load_sequential
	--- PASS: ExampleThread_Load_sequential (0.00s)
	=== RUN   ExampleThread_Load_parallel
	--- PASS: ExampleThread_Load_parallel (0.00s)
	=== RUN   ExampleThread_Load_parallelCycle
	--- PASS: ExampleThread_Load_parallelCycle (0.00s)
	FAIL
	exit status 1
	FAIL	github.com/wdamron/skylark	0.033s